# Generated by Django 5.2.4 on 2025-07-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='eco_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
