# Generated by Django 5.2.4 on 2025-07-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='delivered', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='delivered', max_length=20),
        ),
    ]
